DROP TABLE IF EXISTS LIVRO;
DROP TABLE IF EXISTS AUTOR;
  
CREATE TABLE LIVRO (
  ID bigint auto_increment,
  NOME VARCHAR(250) NOT NULL,
  QUANTIDADEPAGINAS INT NOT NULL,
  AUTOR_ID INT NOT NULL
);

CREATE TABLE AUTOR (
  ID bigint auto_increment,
  NOME VARCHAR(250) NOT NULL
);